import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateWalletLedger1766153840929 implements MigrationInterface {
    name = 'CreateWalletLedger1766153840929'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sellers" DROP CONSTRAINT "sellers_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "seller_listings" DROP CONSTRAINT "seller_listings_product_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "seller_listings" DROP CONSTRAINT "seller_listings_seller_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "inventory_transactions_listing_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_buyer_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_seller_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_order_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_listing_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_product_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "payments_order_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sellers_lifecycle"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sellers_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sellers_rating"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_sku"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_listings_product"`);
        await queryRunner.query(`DROP INDEX "public"."idx_listings_seller"`);
        await queryRunner.query(`DROP INDEX "public"."idx_listings_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_listings_price"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inv_txn_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inv_txn_listing"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inv_txn_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inv_txn_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_buyer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_seller"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_state"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_items_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_items_listing"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_gateway_txn"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_idempotency"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_method"`);
        await queryRunner.query(`DROP INDEX "public"."idx_events_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_events_aggregate"`);
        await queryRunner.query(`DROP INDEX "public"."idx_events_processed"`);
        await queryRunner.query(`DROP INDEX "public"."idx_events_sequence"`);
        await queryRunner.query(`DROP INDEX "public"."idx_events_created"`);
        await queryRunner.query(`ALTER TABLE "seller_listings" DROP CONSTRAINT "seller_listings_product_id_seller_id_key"`);
        await queryRunner.query(`CREATE TABLE "seller_wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sellerId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_06e3a1ce0f678cc833cb90667ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5a3fb26ab29651bced9dab7a44" ON "seller_wallets" ("sellerId") `);
        await queryRunner.query(`CREATE TYPE "public"."wallet_ledger_type_enum" AS ENUM('CREDIT', 'DEBIT')`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_ledger_status_enum" AS ENUM('LOCKED', 'AVAILABLE', 'PAID_OUT')`);
        await queryRunner.query(`CREATE TABLE "wallet_ledger" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sellerId" uuid NOT NULL, "orderId" uuid, "amount" numeric(12,2) NOT NULL, "type" "public"."wallet_ledger_type_enum" NOT NULL, "status" "public"."wallet_ledger_status_enum" NOT NULL, "reason" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d925214b1961738af45cc6959af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_75d800c5223bbea81955509e7d" ON "wallet_ledger" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_98299dfd3def63160000dcf2fc" ON "wallet_ledger" ("sellerId") `);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "processed_at"`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "sequence_number"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying`);
        await queryRunner.query(`UPDATE "users" SET "email" = 'placeholder@example.com' WHERE "email" IS NULL`);
        await queryRunner.query(`
  UPDATE "users"
  SET "email" = concat('placeholder_', id, '@example.com')
  WHERE "email" = 'placeholder@example.com'
`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_phone_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying`);
        await queryRunner.query(`UPDATE "users" SET "password_hash" = 'changeme' WHERE "password_hash" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password_hash" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('BUYER', 'SELLER', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL DEFAULT 'BUYER'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'DELETED')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "phone_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "metadata" SET NOT NULL`);
        // Drop the column if it exists
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "business_name"`);
        // Add as nullable first
        await queryRunner.query(`ALTER TABLE "sellers" ADD "business_name" character varying`);
        // Fill existing rows with placeholder
        await queryRunner.query(`UPDATE "sellers" SET "business_name" = concat('Business_', id) WHERE "business_name" IS NULL`);
        // Set NOT NULL constraint
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "business_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "business_type"`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_business_type_enum" AS ENUM('INDIVIDUAL', 'PARTNERSHIP', 'COMPANY', 'PROPRIETORSHIP')`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "business_type" "public"."sellers_business_type_enum"`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "tax_id"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "tax_id" character varying`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "lifecycle_state"`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_lifecycle_state_enum" AS ENUM('APPLIED', 'UNDER_REVIEW', 'VERIFIED', 'ACTIVE', 'SUSPENDED', 'BANNED')`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "lifecycle_state" "public"."sellers_lifecycle_state_enum" NOT NULL DEFAULT 'APPLIED'`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "verified_by"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "verified_by" character varying`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "contact_phone"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "contact_phone" character varying`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "contact_email"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "contact_email" character varying`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "bank_account_number"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "bank_account_number" character varying`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "bank_ifsc"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "bank_ifsc" character varying`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "bank_name"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "bank_name" character varying`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "rating" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "rating" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "total_orders" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "fulfilled_orders" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "return_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "return_rate" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "reliability_score" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "featured" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "verified_badge" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "products_sku_key"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "sku"`);
        // Add as nullable first
        await queryRunner.query(`ALTER TABLE "products" ADD "sku" character varying`);
        // Fill existing rows with placeholder
        await queryRunner.query(`UPDATE "products" SET "sku" = concat('SKU_', id) WHERE "sku" IS NULL`);
        // Set NOT NULL constraint
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "sku" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327" UNIQUE ("sku")`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "brand"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "brand" character varying`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "category_id" character varying`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "mongo_ref"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "mongo_ref" character varying`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "stock_quantity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "reserved_quantity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "low_stock_threshold" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" DROP COLUMN "condition"`);
        await queryRunner.query(`CREATE TYPE "public"."seller_listings_condition_enum" AS ENUM('NEW', 'REFURBISHED', 'USED')`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ADD "condition" "public"."seller_listings_condition_enum" NOT NULL DEFAULT 'NEW'`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "warranty_months" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "return_window_days" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."seller_listings_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'INACTIVE', 'OUT_OF_STOCK')`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ADD "status" "public"."seller_listings_status_enum" NOT NULL DEFAULT 'DRAFT'`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "processing_time_hours" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_transactions_type_enum" AS ENUM('STOCK_IN', 'STOCK_OUT', 'RESERVED', 'RELEASED', 'ADJUSTMENT', 'DAMAGED', 'RETURNED')`);
        // Add as nullable first
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "type" "public"."inventory_transactions_type_enum"`);
        // Fill existing rows with a default value
        await queryRunner.query(`UPDATE "inventory_transactions" SET "type" = 'STOCK_IN' WHERE "type" IS NULL`);
        // Set NOT NULL constraint
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "order_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "order_id" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "reference_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "reference_id" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "created_by" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_order_number_key"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "order_number"`);
        // Add as nullable first
        await queryRunner.query(`ALTER TABLE "orders" ADD "order_number" character varying`);
        // Fill existing rows with placeholder
        await queryRunner.query(`UPDATE "orders" SET "order_number" = concat('ORDER_', id) WHERE "order_number" IS NULL`);
        // Set NOT NULL constraint
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "order_number" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "UQ_75eba1c6b1a66b09f2a97e6927b" UNIQUE ("order_number")`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "state"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_state_enum" AS ENUM('CREATED', 'PAYMENT_PENDING', 'PAID', 'CONFIRMED', 'PACKED', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURN_APPROVED', 'RETURNED', 'REFUND_INITIATED', 'REFUNDED', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "state" "public"."orders_state_enum" NOT NULL DEFAULT 'CREATED'`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "previous_state"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_previous_state_enum" AS ENUM('CREATED', 'PAYMENT_PENDING', 'PAID', 'CONFIRMED', 'PACKED', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURN_APPROVED', 'RETURNED', 'REFUND_INITIATED', 'REFUNDED', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "previous_state" "public"."orders_previous_state_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "state_changed_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "state_changed_at" SET DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "tax_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "shipping_charge" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "discount_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "tracking_number"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "tracking_number" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "carrier"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "carrier" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "product_name"`);
        // Add as nullable first
        await queryRunner.query(`ALTER TABLE "order_items" ADD "product_name" character varying`);
        // Fill existing rows with placeholder
        await queryRunner.query(`UPDATE "order_items" SET "product_name" = concat('Product_', id) WHERE "product_name" IS NULL`);
        // Set NOT NULL constraint
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "product_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "product_sku"`);
        // Add as nullable first
        await queryRunner.query(`ALTER TABLE "order_items" ADD "product_sku" character varying`);
        // Fill existing rows with placeholder
        await queryRunner.query(`UPDATE "order_items" SET "product_sku" = concat('SKU_', id) WHERE "product_sku" IS NULL`);
        // Set NOT NULL constraint
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "product_sku" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "fulfilled_quantity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "payment_gateway"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "payment_gateway" character varying`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "payments_gateway_transaction_id_key"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "gateway_transaction_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "gateway_transaction_id" character varying`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "UQ_df19fdcdda2cc58abb42d2a8335" UNIQUE ("gateway_transaction_id")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "gateway_order_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "gateway_order_id" character varying`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "currency" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "method"`);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('CARD', 'UPI', 'NET_BANKING', 'WALLET', 'COD')`);
        // Add as nullable first
        await queryRunner.query(`ALTER TABLE "payments" ADD "method" "public"."payments_method_enum"`);
        // Fill existing rows with a placeholder
        await queryRunner.query(`UPDATE "payments" SET "method" = 'CARD' WHERE "method" IS NULL`);
        // Set NOT NULL constraint
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "method" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED')`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "payments_idempotency_key_key"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "idempotency_key"`);
        // Add as nullable first
        await queryRunner.query(`ALTER TABLE "payments" ADD "idempotency_key" character varying`);
        // Fill existing rows with a placeholder
        await queryRunner.query(`UPDATE "payments" SET "idempotency_key" = concat('IDEMP_', id) WHERE "idempotency_key" IS NULL`);
        // Set NOT NULL constraint
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "idempotency_key" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "UQ_59dcef70bd19850783c84f840e5" UNIQUE ("idempotency_key")`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "refund_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "refund_reference"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "refund_reference" character varying`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "event_type"`);
        // Add as nullable first
        await queryRunner.query(`ALTER TABLE "events" ADD "event_type" character varying`);
        // Fill existing rows with a placeholder
        await queryRunner.query(`UPDATE "events" SET "event_type" = 'PLACEHOLDER' WHERE "event_type" IS NULL`);
        // Set NOT NULL constraint
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "event_type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "aggregate_type"`);
        // Add as nullable first
        await queryRunner.query(`ALTER TABLE "events" ADD "aggregate_type" character varying`);
        // Fill existing rows with a placeholder
        await queryRunner.query(`UPDATE "events" SET "aggregate_type" = 'PLACEHOLDER' WHERE "aggregate_type" IS NULL`);
        // Set NOT NULL constraint
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "aggregate_type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "metadata" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "processed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "processing_attempts" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_3676155292d72c67cd4e090514" ON "users" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce7a63022ec99c0534621f9d99" ON "sellers" ("lifecycle_state") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a610bdae3d3dabbae0bfebe8b" ON "sellers" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_c44ac33a05b144dd0d9ddcf932" ON "products" ("sku") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a5f6868c96e0069e699f33e12" ON "products" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e7397490c2bc2c78786c72558" ON "seller_listings" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9d099b3ed635ba8ef52f9711e" ON "seller_listings" ("seller_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_86bfbb48afa756ff764749050d" ON "seller_listings" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_632dcb73f5ffafcf3c913d40be" ON "seller_listings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_58e8a4afe580906e1787fda194" ON "inventory_transactions" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f547886ce56d6470806b4606f5" ON "inventory_transactions" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_23afde96676fc44e4e554968c9" ON "inventory_transactions" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_75eba1c6b1a66b09f2a97e6927" ON "orders" ("order_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e90e93d0e036c3fadbaefa4d0" ON "orders" ("buyer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef6710c78c6fbc26d1ba58268a" ON "orders" ("seller_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c97ed5e639aa4e53ae1ba96ec5" ON "orders" ("state") `);
        await queryRunner.query(`CREATE INDEX "IDX_145532db85752b29c57d2b7b1f" ON "order_items" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fdbe13a4fb1c4d9125e36c1443" ON "order_items" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b2f7b823a21562eeca20e72b00" ON "payments" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_df19fdcdda2cc58abb42d2a833" ON "payments" ("gateway_transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c0d278140eb683b4a6302d746" ON "payments" ("method") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_59dcef70bd19850783c84f840e" ON "payments" ("idempotency_key") `);
        await queryRunner.query(`ALTER TABLE "sellers" ADD CONSTRAINT "FK_83f4670f0e114d0be3731bade87" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ADD CONSTRAINT "FK_3e7397490c2bc2c78786c72558f" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ADD CONSTRAINT "FK_a9d099b3ed635ba8ef52f9711e9" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_58e8a4afe580906e1787fda194b" FOREIGN KEY ("listing_id") REFERENCES "seller_listings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_5e90e93d0e036c3fadbaefa4d0a" FOREIGN KEY ("buyer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_ef6710c78c6fbc26d1ba58268ab" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_fdbe13a4fb1c4d9125e36c14433" FOREIGN KEY ("listing_id") REFERENCES "seller_listings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_fdbe13a4fb1c4d9125e36c14433"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_ef6710c78c6fbc26d1ba58268ab"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_5e90e93d0e036c3fadbaefa4d0a"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_58e8a4afe580906e1787fda194b"`);
        await queryRunner.query(`ALTER TABLE "seller_listings" DROP CONSTRAINT "FK_a9d099b3ed635ba8ef52f9711e9"`);
        await queryRunner.query(`ALTER TABLE "seller_listings" DROP CONSTRAINT "FK_3e7397490c2bc2c78786c72558f"`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP CONSTRAINT "FK_83f4670f0e114d0be3731bade87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59dcef70bd19850783c84f840e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c0d278140eb683b4a6302d746"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df19fdcdda2cc58abb42d2a833"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2f7b823a21562eeca20e72b00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fdbe13a4fb1c4d9125e36c1443"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_145532db85752b29c57d2b7b1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c97ed5e639aa4e53ae1ba96ec5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef6710c78c6fbc26d1ba58268a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e90e93d0e036c3fadbaefa4d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75eba1c6b1a66b09f2a97e6927"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23afde96676fc44e4e554968c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f547886ce56d6470806b4606f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58e8a4afe580906e1787fda194"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_632dcb73f5ffafcf3c913d40be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86bfbb48afa756ff764749050d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9d099b3ed635ba8ef52f9711e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e7397490c2bc2c78786c72558"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a5f6868c96e0069e699f33e12"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c44ac33a05b144dd0d9ddcf932"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a610bdae3d3dabbae0bfebe8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce7a63022ec99c0534621f9d99"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3676155292d72c67cd4e090514"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "processing_attempts" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "processed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "metadata" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "aggregate_type"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "aggregate_type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "event_type"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "event_type" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "refund_reference"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "refund_reference" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "refund_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "UQ_59dcef70bd19850783c84f840e5"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "idempotency_key"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "idempotency_key" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "payments_idempotency_key_key" UNIQUE ("idempotency_key")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "status" character varying(50) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "method"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "method" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "currency" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "gateway_order_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "gateway_order_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "UQ_df19fdcdda2cc58abb42d2a8335"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "gateway_transaction_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "gateway_transaction_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "payments_gateway_transaction_id_key" UNIQUE ("gateway_transaction_id")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "payment_gateway"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "payment_gateway" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "fulfilled_quantity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "product_sku"`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "product_sku" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "product_name"`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "product_name" character varying(500) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "carrier"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "carrier" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "tracking_number"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "tracking_number" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "discount_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "shipping_charge" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "tax_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "state_changed_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "state_changed_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "previous_state"`);
        await queryRunner.query(`DROP TYPE "public"."orders_previous_state_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "previous_state" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "state"`);
        await queryRunner.query(`DROP TYPE "public"."orders_state_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "state" character varying(50) NOT NULL DEFAULT 'CREATED'`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "UQ_75eba1c6b1a66b09f2a97e6927b"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "order_number"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "order_number" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_order_number_key" UNIQUE ("order_number")`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "created_by" uuid`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "reference_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "reference_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "order_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "order_id" uuid`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_transactions_type_enum"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "processing_time_hours" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."seller_listings_status_enum"`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ADD "status" character varying(50) DEFAULT 'DRAFT'`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "return_window_days" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "warranty_months" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" DROP COLUMN "condition"`);
        await queryRunner.query(`DROP TYPE "public"."seller_listings_condition_enum"`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ADD "condition" character varying(50) DEFAULT 'NEW'`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "low_stock_threshold" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "reserved_quantity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ALTER COLUMN "stock_quantity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "mongo_ref"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "mongo_ref" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "category_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "brand"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "brand" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "sku" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "products_sku_key" UNIQUE ("sku")`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "verified_badge" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "featured" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "reliability_score" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "return_rate" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "return_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "fulfilled_orders" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "total_orders" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "rating" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "sellers" ALTER COLUMN "rating" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "bank_name"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "bank_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "bank_ifsc"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "bank_ifsc" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "bank_account_number"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "bank_account_number" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "contact_email"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "contact_email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "contact_phone"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "contact_phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "verified_by"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "verified_by" uuid`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "lifecycle_state"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_lifecycle_state_enum"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "lifecycle_state" character varying(50) NOT NULL DEFAULT 'APPLIED'`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "tax_id"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "tax_id" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "business_type"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_business_type_enum"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "business_type" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP COLUMN "business_name"`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD "business_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "metadata" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "phone_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(20) NOT NULL DEFAULT 'BUYER'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_a000cca60bcf04454e727699490"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_phone_key" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255)`);
        await queryRunner.query(`UPDATE "users" SET "email" = concat('placeholder_', id, '@example.com') WHERE "email" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "events" ADD "sequence_number" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ADD "processed_at" TIMESTAMP`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98299dfd3def63160000dcf2fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75d800c5223bbea81955509e7d"`);
        await queryRunner.query(`DROP TABLE "wallet_ledger"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_ledger_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_ledger_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a3fb26ab29651bced9dab7a44"`);
        await queryRunner.query(`DROP TABLE "seller_wallets"`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ADD CONSTRAINT "seller_listings_product_id_seller_id_key" UNIQUE ("product_id", "seller_id")`);
        await queryRunner.query(`CREATE INDEX "idx_events_created" ON "events" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_events_sequence" ON "events" ("sequence_number") `);
        await queryRunner.query(`CREATE INDEX "idx_events_processed" ON "events" ("processed", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_events_aggregate" ON "events" ("aggregate_type", "aggregate_id") `);
        await queryRunner.query(`CREATE INDEX "idx_events_type" ON "events" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_method" ON "payments" ("method") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_idempotency" ON "payments" ("idempotency_key") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_gateway_txn" ON "payments" ("gateway_transaction_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_status" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_order" ON "payments" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_order_items_listing" ON "order_items" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "idx_order_items_order" ON "order_items" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_number" ON "orders" ("order_number") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_created" ON "orders" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_state" ON "orders" ("state") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_seller" ON "orders" ("seller_id") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_buyer" ON "orders" ("buyer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_inv_txn_created" ON "inventory_transactions" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_inv_txn_order" ON "inventory_transactions" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_inv_txn_listing" ON "inventory_transactions" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "idx_inv_txn_type" ON "inventory_transactions" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_listings_price" ON "seller_listings" ("price") `);
        await queryRunner.query(`CREATE INDEX "idx_listings_status" ON "seller_listings" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_listings_seller" ON "seller_listings" ("seller_id") `);
        await queryRunner.query(`CREATE INDEX "idx_listings_product" ON "seller_listings" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_products_category" ON "products" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_products_sku" ON "products" ("sku") `);
        await queryRunner.query(`CREATE INDEX "idx_sellers_rating" ON "sellers" ("rating") `);
        await queryRunner.query(`CREATE INDEX "idx_sellers_user_id" ON "sellers" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_sellers_lifecycle" ON "sellers" ("lifecycle_state") `);
        await queryRunner.query(`CREATE INDEX "idx_users_status" ON "users" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_users_role" ON "users" ("role") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "payments_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_listing_id_fkey" FOREIGN KEY ("listing_id") REFERENCES "seller_listings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_seller_id_fkey" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_buyer_id_fkey" FOREIGN KEY ("buyer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_listing_id_fkey" FOREIGN KEY ("listing_id") REFERENCES "seller_listings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ADD CONSTRAINT "seller_listings_seller_id_fkey" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_listings" ADD CONSTRAINT "seller_listings_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD CONSTRAINT "sellers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
